version: '3'

services:

  pagehitmongo:
    image: mongo:5
    env_file: .env
    container_name: pagehitmongo
    volumes:
      - data:/data/db
    ports:
      - "${MONGO_INITDB_PORT}:27017"
  adminer:
    image: adminer:latest
    env_file: .env
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  data:
